### ISSUE TITLE
CI combinations

### ISSUE THREAD

**Issue by michael-loki** [loki-project/loki-network#717]
Please add below what CI combinations we want.

Matrix combinations include:

- OS
- compiler
- shared/static
- build flags
- cross compile

**Comment by majestrate** [comment]
i want `make windows` cross compile target to function.

**Comment by despair86** [comment]
- 64-bit Windows 10
- GCC 8.3
- mixed (static local dependencies, dynamic system libs)
- not quite sure yet
- recommended, but native builds work under MSYS2

I'll take over 32-bit support myself, and you can focus 64-builds

**Comment by despair86** [comment]
Honestly, I don't really recommend using Microsoft C++ in the first place

**Comment by neuroscr** [comment]
Keep in mind we have the VM on the dev box that can work with GitLab CI

**Comment by despair86** [comment]
yeah exactly, i set up 32-bit build system (and a 64-bit cross compiler for this) @neuroscr

**Comment by despair86** [comment]
@majestrate eh invoking cmake directly isn't that much harder

**Comment by despair86** [comment]
but yes @michael-loki keep me posted on your progress

**Comment by michael-loki** [comment]
#708 is tracking the windows stuff

**Comment by neuroscr** [comment]
All final release build types (static? native compile?) should be built/tested

**Comment by neuroscr** [comment]
Michael says we're currently happy with:
```
matrix:
  fast_finish: true
  include:
  - name: "lint check"
    os: linux
    dist: xenial
    compiler: gcc
    env: MAKE_TARGET=format-verify PATH="/usr/lib/llvm-8/bin:$PATH"
    addons:
      apt:
        sources:
          - llvm-toolchain-xenial-8
        packages:
          - clang-format-8
  - name: "make debug (linux/gcc)"
    os: linux
    dist: xenial
    compiler: gcc
    env: BUILD_TYPE=Debug IS_NOTIFICATION=1
  - name: "make release (linux/gcc)"
    os: linux
    dist: xenial
    compiler: gcc
    env: BUILD_TYPE=Release
  - name: "make debug (linux/clang)"
    os: linux
    dist: xenial
    compiler: clang
    env: BUILD_TYPE=Debug
  - name: "make release (linux/clang)"
    os: linux
    dist: xenial
    compiler: clang
    env: BUILD_TYPE=Release
  - name: "make debug (macOS/clang)"
    os: osx
    osx_image: xcode10.2
    env: BUILD_TYPE=Debug PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: "make release (macOS/clang)"
    os: osx
    osx_image: xcode10.2
    env: BUILD_TYPE=Release PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: "make windows (macOS)"
    os: osx
    osx_image: xcode10.2
    env: MAKE_TARGET=windows PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: "make windows-release (macOS)"
    os: osx
    osx_image: xcode10.2
    env: MAKE_TARGET=windows-release PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: "make release (macOS beta/clang)"
    os: osx
    osx_image: xcode11
    env: BUILD_TYPE=Release PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: "address sanitizer"
    os: osx
    osx_image: xcode10.2
    env: BUILD_TYPE=Debug ASAN=ON PATH="/usr/local/opt/ccache/libexec:$PATH" CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++
  - name: "native windows debug"
    os: windows
    env: BUILD_TYPE=Debug
  - name: "native windows release"
    os: windows
    env: BUILD_TYPE=Release
  - name: "router docker image"
    os: linux
    dist: xenial
    env: DOCKER_FILE=docker/router.Dockerfile
    services: docker
  - name: "make windows docker image"
    os: linux
    dist: xenial
    env: DOCKER_FILE=docker/alpine-windows.Dockerfile
    services: docker
  - name: "gcc trunk"
    os: linux
    dist: xenial
    env: DOCKER_FILE=docker/gcc-trunk.Dockerfile
    services: docker
  allow_failures:
  - os: linux
    dist: xenial
    env: DOCKER_FILE=docker/alpine-windows.Dockerfile
    services: docker
  - os: linux
    dist: xenial
    env: DOCKER_FILE=docker/gcc-trunk.Dockerfile
    services: docker
  - os: osx
    osx_image: xcode10.2
    env: MAKE_TARGET=windows PATH="/usr/local/opt/ccache/libexec:$PATH"
  - os: osx
    osx_image: xcode10.2
    env: MAKE_TARGET=windows-release PATH="/usr/local/opt/ccache/libexec:$PATH"

env:
  global:
    - NINJA=ninja
    - STATIC_LINK=OFF
```
